import React, {useState} from "react";
import Head from "next/head";

export default function SearchTemplates() {
    const [query, setQuery] = React.useState("");

    const handleSubmit = async () => {
        try {
            const response = await fetch('api/code-templates/search', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    query: query
                })
            });

            if (!response.ok) {
                throw new Error('Network response was not ok');
            }

            const data = await response.json();

            // asked chatgpt "how to access the parsed data from the response so that i can pick and choose what to display to the user in the UI" 
            const formatTemplates = (templates) => {
                return templates.map(template => {
                    const tags = template.tags.map(tag => tag.name).join(", ");
                    return `Title: ${template.title}\nExplanation: ${template.explanation}\nCode:\n${template.code}\nTags: ${tags}\n`; // Limit code preview
                }).join("\n");
            };
            
            document.getElementById("temps").innerHTML = formatTemplates(data.codeTemplates);
      
        } catch (error) {
            console.error("Error searching for templates:", error);
        }
    };

    const onClick = () => {
        handleSubmit();
    };

    return (
        <>
            <Head>
                <title>Scriptorium</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <section className="grid grid-cols-1 bg-white py-16 gap-5">
                    <div className="container mx-auto bg-violet-900 p-6 rounded-lg shadow-md">
                        <h2 className="text-2xl font-semibold mb-2">Search Templates</h2>
                        <div className="grid grid-cols-1 gap-5">
                            <input type="search" id="default-search" className="block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search Templates..." required onChange={(e) => setQuery(e.target.value)}/>
                            <button className="h-10 md:h-16 rounded-lg bg-violet-950 hover:bg-violet-400" onClick={() => onClick()}>
                                {"Search Templates"}
                            </button>
                        </div>
                    </div>

                    <div className="container mx-auto bg-violet-900 p-6 rounded-lg shadow-md whitespace-pre-line">
                        <p id="temps"></p>
                    </div>
                </section>
            </main>
        </>
    )
}